branch-defaults:
  ajax:
    environment: food-test
environment-defaults:
  food-test:
    branch: null
    repository: null
global:
  application_name: food
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-east-2::platform/Python 3.4 running
    on 64bit Amazon Linux/2.4.2
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
